### PR TITLE
C3 visualizations

### PR DESCRIPTION
**Pull request by YuRiTan**

### CODE REVIEW

**Comment by daaf89** [comment]
Ganz geil

**Comment by YuRiTan** [comment]
we have to fix the following error first: "TypeError: Object of type 'MagicMock' is not JSON serializable"  in test_app.py

**Comment by YuRiTan** [comment]
in the app.py, we do some json.dumps. This causes issues with the mocking post in the test_app.py, since this mocked object cannot be "json dumped" (json serialized). We could refactor this into the statistics.py, but i think the json transforming part is not the responsibility of the statistics module. On the other hand, it is the most easy solution (which could replace the quick fix implemented now)

**Comment by YuRiTan** [comment]
weird thing is that it works locally, but fails on travis

**Comment by YuRiTan** [comment]
solution was that the mocking part in the integrationtest in test_app.py was not mocking the replier part...

@daaf89 Can you review the PR?

**Pull request merged**
